"""Add current_stage to permit_requests

Revision ID: 0021065a1e01
Revises: 139c2d9559bd
Create Date: 2025-09-07 11:34:35.626422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0021065a1e01'
down_revision = '139c2d9559bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permit_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permit_requests', schema=None) as batch_op:
        batch_op.drop_column('current_stage')

    # ### end Alembic commands ###
