"""Moved tracking_id to TravelLog and added travel_logs table

Revision ID: 0061934e3b7f
Revises: 91c12c546aef
Create Date: 2025-05-22 23:52:37.934496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0061934e3b7f'
down_revision = '91c12c546aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', name='travel_status_enum'), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('tracking_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['travel_order_id'], ['travel_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.drop_column('tracking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_id', mysql.VARCHAR(length=50), nullable=True))

    op.drop_table('travel_logs')
    # ### end Alembic commands ###
