"""Add remarks field to IssueReport

Revision ID: 02b2751ec5d6
Revises: ef69ccd01e67
Create Date: 2025-05-24 00:36:53.325292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b2751ec5d6'
down_revision = 'ef69ccd01e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
