"""Add assigned_department to JobOrderDetails

Revision ID: 0bdaf396cab0
Revises: 850603c2d818
Create Date: 2025-05-20 14:17:59.167760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdaf396cab0'
down_revision = '850603c2d818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['assigned_department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_order_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_department_id')

    # ### end Alembic commands ###
