"""Remove OPCR

Revision ID: 0d44deb8dcce
Revises: 323c8bacfdd8
Create Date: 2025-06-27 23:41:17.296742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d44deb8dcce'
down_revision = '323c8bacfdd8'
branch_labels = None
depends_on = None


def upgrade():
    # Drop foreign key constraints and referencing columns FIRST
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_constraint('ai_insights_ibfk_2', type_='foreignkey')
        batch_op.drop_column('opcr_id')

    with op.batch_alter_table('evaluation_sections', schema=None) as batch_op:
        batch_op.drop_constraint('evaluation_sections_ibfk_2', type_='foreignkey')
        batch_op.drop_column('opcr_id')

    # Now it's safe to drop the 'opcrs' table
    op.drop_table('opcrs')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opcr_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('evaluation_sections_ibfk_2', 'opcrs', ['opcr_id'], ['id'])

    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opcr_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('ai_insights_ibfk_2', 'opcrs', ['opcr_id'], ['id'])

    op.create_table('opcrs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('period_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('submitted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('graded', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('final_overall_rating', mysql.FLOAT(), nullable=True),
    sa.Column('final_average_rating', mysql.FLOAT(), nullable=True),
    sa.Column('adjective_rating', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='opcrs_ibfk_1'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='opcrs_ibfk_2'),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], name='opcrs_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
