"""Flatten Applicant model

Revision ID: 1112000124e2
Revises: a42f43fc07e0
Create Date: 2025-09-29 00:54:02.452361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1112000124e2'
down_revision = 'a42f43fc07e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicant_eligibility')
    op.drop_table('applicant_voluntary_work')
    op.drop_table('applicant_other_info')
    op.drop_table('applicant_work_experience')
    op.drop_table('applicant_training')
    op.drop_table('applicant_education')
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('work_experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('eligibility', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('voluntary_work', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('trainings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('other_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recognitions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('memberships', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_column('memberships')
        batch_op.drop_column('recognitions')
        batch_op.drop_column('other_skills')
        batch_op.drop_column('trainings')
        batch_op.drop_column('voluntary_work')
        batch_op.drop_column('eligibility')
        batch_op.drop_column('work_experience')
        batch_op.drop_column('education')

    op.create_table('applicant_education',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('applicant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('level', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('school_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('course', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('year_graduated', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('honors', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('applicant_education_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applicant_training',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('applicant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('applicant_training_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applicant_work_experience',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('applicant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('position_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('status_of_appointment', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('monthly_salary', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('applicant_work_experience_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applicant_other_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('applicant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('skills', mysql.TEXT(), nullable=True),
    sa.Column('recognitions', mysql.TEXT(), nullable=True),
    sa.Column('memberships', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('applicant_other_info_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applicant_voluntary_work',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('applicant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('organization_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('applicant_voluntary_work_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applicant_eligibility',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('applicant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('exam_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('rating', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date_of_exam', sa.DATE(), nullable=True),
    sa.Column('place_of_exam', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('license_number', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('applicant_eligibility_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
