"""Add date_hired to JobOrderDetails

Revision ID: 1b51e8a71b93
Revises: 79f1139cf9d1
Create Date: 2025-06-20 12:13:24.743045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b51e8a71b93'
down_revision = '79f1139cf9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_hired', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_order_details', schema=None) as batch_op:
        batch_op.drop_column('date_hired')

    # ### end Alembic commands ###
