"""Move department assignment to casual employee details only

Revision ID: 1eedb2e27971
Revises: 9ee601f54ef7
Create Date: 2025-05-01 23:26:12.129853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eedb2e27971'
down_revision = '9ee601f54ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casual_employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['assigned_department_id'], ['id'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('employment_status')

    with op.batch_alter_table('casual_employee_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_department_id')

    # ### end Alembic commands ###
