"""Add date_submitted to IPCR

Revision ID: 20d5b85d30bf
Revises: 0d44deb8dcce
Create Date: 2025-07-08 22:42:13.327936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d5b85d30bf'
down_revision = '0d44deb8dcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcrs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_submitted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcrs', schema=None) as batch_op:
        batch_op.drop_column('date_submitted')

    # ### end Alembic commands ###
