"""Add AI insight columns to Applicant model

Revision ID: 2891444f79c0
Revises: 349f4c940c1d
Create Date: 2025-05-04 22:39:16.605394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2891444f79c0'
down_revision = '349f4c940c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('resume_match', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extracted_education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extracted_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extracted_experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weaknesses', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('skills')
        batch_op.drop_column('weaknesses')
        batch_op.drop_column('strengths')
        batch_op.drop_column('extracted_experience')
        batch_op.drop_column('extracted_skills')
        batch_op.drop_column('extracted_education')
        batch_op.drop_column('resume_match')
        batch_op.drop_column('application_score')

    # ### end Alembic commands ###
