"""Create JobOrderHistory table

Revision ID: 2e5a52cd0e0d
Revises: f2bafa37cad9
Create Date: 2025-09-02 16:35:48.941217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5a52cd0e0d'
down_revision = 'f2bafa37cad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=100), nullable=True),
    sa.Column('assigned_department_id', sa.Integer(), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_order_details', schema=None) as batch_op:
        batch_op.drop_column('contract_end')
        batch_op.drop_column('contract_start')

    op.drop_table('job_order_history')
    # ### end Alembic commands ###
