"""Add number_of_openings to JobPosting

Revision ID: 349f4c940c1d
Revises: a1c0e0587d6e
Create Date: 2025-05-03 19:56:12.469049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349f4c940c1d'
down_revision = 'a1c0e0587d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_openings', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('number_of_openings')

    # ### end Alembic commands ###
