"""Add message file

Revision ID: 35593d83578d
Revises: 21fd1aad4f7d
Create Date: 2025-06-11 23:24:22.808269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35593d83578d'
down_revision = '21fd1aad4f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_attachments')
    # ### end Alembic commands ###
