"""Add PermanentSalaryHistory and BenefitEligibility tables

Revision ID: 3687ad58e085
Revises: 1b51e8a71b93
Create Date: 2025-06-21 00:02:02.620072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3687ad58e085'
down_revision = '1b51e8a71b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permanent_benefit_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permanent_employee_id', sa.Integer(), nullable=False),
    sa.Column('benefit_name', sa.String(length=100), nullable=False),
    sa.Column('eligibility_years', sa.Integer(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=True),
    sa.Column('eligible_since', sa.Date(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('checked_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['permanent_employee_id'], ['permanent_employee_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permanent_salary_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permanent_employee_id', sa.Integer(), nullable=False),
    sa.Column('previous_salary', sa.String(length=50), nullable=True),
    sa.Column('new_salary', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permanent_employee_id'], ['permanent_employee_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permanent_salary_history')
    op.drop_table('permanent_benefit_eligibility')
    # ### end Alembic commands ###
