"""Change resume_match to Text

Revision ID: 36c46475ef92
Revises: 635725609a33
Create Date: 2025-06-01 21:15:44.449598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36c46475ef92'
down_revision = '635725609a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('resume_match',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('resume_match',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
