"""Add training recommendations to AIInsight

Revision ID: 3b6025c656dd
Revises: 02b2751ec5d6
Create Date: 2025-05-25 11:34:32.818196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6025c656dd'
down_revision = '02b2751ec5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_training_recommendations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_column('ai_training_recommendations')

    # ### end Alembic commands ###
