"""Add previous_grade and new_grade columns to PermanentSalaryHistory

Revision ID: 4ac01bf27b2e
Revises: 1112000124e2
Create Date: 2025-10-08 13:23:44.513978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac01bf27b2e'
down_revision = '1112000124e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permanent_salary_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_grade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permanent_salary_history', schema=None) as batch_op:
        batch_op.drop_column('new_grade')
        batch_op.drop_column('previous_grade')

    # ### end Alembic commands ###
