"""Updated Employee model

Revision ID: 545b5a1555c2
Revises: b3418326fef8
Create Date: 2025-04-20 13:07:18.452399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '545b5a1555c2'
down_revision = 'b3418326fef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('middle_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('salary_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('authorized_salary', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('actual_salary', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('area_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('area_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eligibility', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('umid_no', sa.String(length=20), nullable=True))
        batch_op.alter_column('item_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('step',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('umid')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('umid', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('step',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('item_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('umid_no')
        batch_op.drop_column('comments')
        batch_op.drop_column('eligibility')
        batch_op.drop_column('area_type')
        batch_op.drop_column('area_code')
        batch_op.drop_column('actual_salary')
        batch_op.drop_column('authorized_salary')
        batch_op.drop_column('salary_grade')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('middle_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
