"""Employee Info Add

Revision ID: 54a77192b2a5
Revises: 545b5a1555c2
Create Date: 2025-04-26 23:57:55.584865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54a77192b2a5'
down_revision = '545b5a1555c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casual_employee_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name_extension', sa.String(length=10), nullable=True),
    sa.Column('position_title', sa.String(length=100), nullable=False),
    sa.Column('equivalent_salary', sa.String(length=100), nullable=True),
    sa.Column('daily_wage', sa.Float(), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permanent_employee_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=20), nullable=False),
    sa.Column('position_title', sa.String(length=100), nullable=False),
    sa.Column('salary_grade', sa.Integer(), nullable=True),
    sa.Column('authorized_salary', sa.String(length=50), nullable=True),
    sa.Column('actual_salary', sa.String(length=50), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('area_code', sa.String(length=20), nullable=True),
    sa.Column('area_type', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('umid_no', sa.String(length=20), nullable=True),
    sa.Column('date_original_appointment', sa.Date(), nullable=True),
    sa.Column('date_last_promotion', sa.Date(), nullable=True),
    sa.Column('eligibility', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type', sa.String(length=50), nullable=False))
        batch_op.alter_column('organizational_unit',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('step')
        batch_op.drop_column('item_number')
        batch_op.drop_column('level')
        batch_op.drop_column('umid_no')
        batch_op.drop_column('area_type')
        batch_op.drop_column('area_code')
        batch_op.drop_column('eligibility')
        batch_op.drop_column('position_title')
        batch_op.drop_column('tin')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('actual_salary')
        batch_op.drop_column('authorized_salary')
        batch_op.drop_column('salary_grade')
        batch_op.drop_column('comments')
        batch_op.drop_column('sex')
        batch_op.drop_column('date_original_appointment')
        batch_op.drop_column('date_last_promotion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_last_promotion', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('date_original_appointment', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('sex', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('comments', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('salary_grade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('authorized_salary', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('actual_salary', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('tin', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('position_title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('eligibility', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('area_code', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('area_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('umid_no', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('item_number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('step', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.alter_column('organizational_unit',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('employment_type')

    op.drop_table('permanent_employee_details')
    op.drop_table('job_order_details')
    op.drop_table('casual_employee_details')
    # ### end Alembic commands ###
