"""Remove employment_type from Employee

Revision ID: 5b98f22491f5
Revises: e8c24aa7c941
Create Date: 2025-04-29 08:27:03.566263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b98f22491f5'
down_revision = 'e8c24aa7c941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('employment_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
