"""Added IPCR and OPCR models with evaluation structure

Revision ID: 61f57844276f
Revises: 5b98f22491f5
Create Date: 2025-04-29 19:05:00.875166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61f57844276f'
down_revision = '5b98f22491f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('graded', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_grade', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipcrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('graded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('opcr_id', sa.Integer(), nullable=True),
    sa.Column('ipcr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ipcr_id'], ['ipcrs.id'], ),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcrs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('mfo', sa.String(length=255), nullable=True),
    sa.Column('success_indicator', sa.Text(), nullable=True),
    sa.Column('allotted_budget', sa.String(length=100), nullable=True),
    sa.Column('accountable', sa.String(length=255), nullable=True),
    sa.Column('accomplishment', sa.Text(), nullable=True),
    sa.Column('rating_q', sa.Float(), nullable=True),
    sa.Column('rating_e', sa.Float(), nullable=True),
    sa.Column('rating_t', sa.Float(), nullable=True),
    sa.Column('rating_a', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['evaluation_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('casual_employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'positions', ['position_id'], ['id'])
        batch_op.drop_column('position_title')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.drop_column('organizational_unit')

    with op.batch_alter_table('permanent_employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'positions', ['position_id'], ['id'])
        batch_op.drop_column('position_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permanent_employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('position_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizational_unit', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('casual_employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('position_id')

    op.drop_table('section_items')
    op.drop_table('evaluation_sections')
    op.drop_table('ipcrs')
    op.drop_table('positions')
    op.drop_table('opcrs')
    op.drop_table('evaluation_periods')
    op.drop_table('departments')
    # ### end Alembic commands ###
