"""Convert label string back to inline enum

Revision ID: 63b09c6d5a9b
Revises: 87d9e213ea39
Create Date: 2025-07-10 12:22:29.603044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63b09c6d5a9b'
down_revision = '87d9e213ea39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('Meeting', 'Training', 'Leave', 'Official Travel', 'Holiday', 'Public Event', 'Administrative'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.Enum('Meeting', 'Training', 'Leave', 'Official Travel', 'Holiday', 'Public Event', 'Administrative'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
