"""Add paid_days to LeaveApplication

Revision ID: 6a397237ba96
Revises: cac75cb0bfb5
Create Date: 2025-09-22 23:08:19.916128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a397237ba96'
down_revision = 'cac75cb0bfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.drop_column('paid_days')

    # ### end Alembic commands ###
