"""Added interview fields to Applicant

Revision ID: 6e6c1eba1c81
Revises: 2891444f79c0
Create Date: 2025-05-08 10:05:36.669724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e6c1eba1c81'
down_revision = '2891444f79c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('interview_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('interview_method', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('interview_notes', sa.Text(), nullable=True))
        batch_op.drop_column('skills')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('skills', mysql.TEXT(), nullable=True))
        batch_op.drop_column('interview_notes')
        batch_op.drop_column('interview_method')
        batch_op.drop_column('interview_time')
        batch_op.drop_column('interview_date')

    # ### end Alembic commands ###
