"""Change TravelOrder.date_departure to DateTime

Revision ID: 73a0822e7ae3
Revises: 63b09c6d5a9b
Create Date: 2025-09-01 08:44:28.920211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a0822e7ae3'
down_revision = '63b09c6d5a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.alter_column('date_departure',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.alter_column('date_departure',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
