"""Remove filepath from MessageAttachment

Revision ID: 79f1139cf9d1
Revises: ce59c4fd0032
Create Date: 2025-06-12 14:27:53.837871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79f1139cf9d1'
down_revision = 'ce59c4fd0032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', mysql.VARCHAR(length=512), nullable=False))

    # ### end Alembic commands ###
