"""Add permit history relationship

Revision ID: 7c18a9b0868b
Revises: 2e5a52cd0e0d
Create Date: 2025-09-04 23:52:47.631853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c18a9b0868b'
down_revision = '2e5a52cd0e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit_request_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_request_id', sa.Integer(), nullable=True),
    sa.Column('action_by', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('Submitted', 'Approved', 'Rejected', name='permit_action_enum'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('signature_snapshot', sa.String(length=255), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['action_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permit_request_id'], ['permit_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('signature_filename')

    op.drop_table('permit_request_history')
    # ### end Alembic commands ###
