"""Update AIInsight model to keep only summary and suggestion

Revision ID: 850603c2d818
Revises: daab3ebbac15
Create Date: 2025-05-19 17:50:27.200544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850603c2d818'
down_revision = 'daab3ebbac15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opcr_id', sa.Integer(), nullable=True),
    sa.Column('ipcr_id', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ipcr_id'], ['ipcrs.id'], ),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcrs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
