"""Temporarily convert label enum to string

Revision ID: 87d9e213ea39
Revises: 20d5b85d30bf
Create Date: 2025-07-10 12:14:49.625278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87d9e213ea39'
down_revision = '20d5b85d30bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=mysql.ENUM('Personal', 'Business', 'Family', 'Holiday', 'ETC'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Personal', 'Business', 'Family', 'Holiday', 'ETC'),
               existing_nullable=False)

    # ### end Alembic commands ###
