"""Add salary to LeaveApplication

Revision ID: 8fec383c977a
Revises: cae2f57b2c9b
Create Date: 2025-05-21 18:13:43.323947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fec383c977a'
down_revision = 'cae2f57b2c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.drop_column('salary')

    # ### end Alembic commands ###
