"""TEST

Revision ID: 91c12c546aef
Revises: e94107c74974
Create Date: 2025-05-22 22:48:43.967390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c12c546aef'
down_revision = 'e94107c74974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.drop_index('uq_tracking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.create_index('uq_tracking_id', ['tracking_id'], unique=True)

    # ### end Alembic commands ###
