"""Create Interview table and update Applicant

Revision ID: 9bce5b6987eb
Revises: 6e6c1eba1c81
Create Date: 2025-05-08 11:24:07.187802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bce5b6987eb'
down_revision = '6e6c1eba1c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('interviewer', sa.String(length=100), nullable=True),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Scheduled', 'Completed', 'Cancelled'), nullable=True),
    sa.Column('result', sa.Enum('Pending', 'Approved', 'Rejected'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_column('interview_time')
        batch_op.drop_column('interview_method')
        batch_op.drop_column('interview_date')
        batch_op.drop_column('interview_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_notes', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('interview_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('interview_method', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('interview_time', mysql.TIME(), nullable=True))

    op.drop_table('interviews')
    # ### end Alembic commands ###
