"""Added number_of_positions to positions

Revision ID: 9ee601f54ef7
Revises: edebab0bc9a5
Create Date: 2025-04-29 21:18:19.936246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee601f54ef7'
down_revision = 'edebab0bc9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_positions', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('number_of_positions')

    # ### end Alembic commands ###
