"""Add position_type to JobPosting

Revision ID: a1c0e0587d6e
Revises: 9d382b6852fe
Create Date: 2025-05-02 11:53:06.307067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c0e0587d6e'
down_revision = '9d382b6852fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_position_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('job_position_type')

    # ### end Alembic commands ###
