"""Add Applicant normalized PDS tables

Revision ID: a42f43fc07e0
Revises: dbcac858f462
Create Date: 2025-09-28 22:32:13.003225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a42f43fc07e0'
down_revision = 'dbcac858f462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('course', sa.String(length=255), nullable=True),
    sa.Column('year_graduated', sa.String(length=10), nullable=True),
    sa.Column('honors', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicant_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('exam_name', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.Column('date_of_exam', sa.Date(), nullable=True),
    sa.Column('place_of_exam', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicant_other_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('recognitions', sa.Text(), nullable=True),
    sa.Column('memberships', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicant_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicant_voluntary_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicant_work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status_of_appointment', sa.String(length=100), nullable=True),
    sa.Column('monthly_salary', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pds_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pds_match', sa.Text(), nullable=True))
        batch_op.drop_column('resume_path')
        batch_op.drop_column('resume_match')
        batch_op.drop_column('extracted_education')
        batch_op.drop_column('extracted_skills')
        batch_op.drop_column('extracted_experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_experience', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('extracted_skills', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('extracted_education', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('resume_match', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('resume_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('pds_match')
        batch_op.drop_column('pds_path')

    op.drop_table('applicant_work_experience')
    op.drop_table('applicant_voluntary_work')
    op.drop_table('applicant_training')
    op.drop_table('applicant_other_info')
    op.drop_table('applicant_eligibility')
    op.drop_table('applicant_education')
    # ### end Alembic commands ###
