"""Add JobLog model

Revision ID: a45e87b3b0b6
Revises: 3687ad58e085
Create Date: 2025-06-21 13:18:18.088296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45e87b3b0b6'
down_revision = '3687ad58e085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_logs')
    # ### end Alembic commands ###
