"""Add Employee model and link to Users

Revision ID: b3418326fef8
Revises: 497874efe110
Create Date: 2025-04-20 13:00:52.677225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3418326fef8'
down_revision = '497874efe110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('organizational_unit', sa.String(length=100), nullable=False),
    sa.Column('position_title', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('item_number', sa.String(length=20), nullable=True),
    sa.Column('step', sa.String(length=10), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('umid', sa.String(length=20), nullable=True),
    sa.Column('date_original_appointment', sa.Date(), nullable=True),
    sa.Column('date_last_promotion', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
