"""Add late_submission flag to IPCR

Revision ID: b7f3b3157e59
Revises: 4ac01bf27b2e
Create Date: 2025-10-14 22:08:35.331361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7f3b3157e59'
down_revision = '4ac01bf27b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcrs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_submission', sa.Boolean(), nullable=True))

    with op.batch_alter_table('permanent_salary_history', schema=None) as batch_op:
        batch_op.drop_column('previous_grade')
        batch_op.drop_column('new_grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permanent_salary_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_grade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_grade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('ipcrs', schema=None) as batch_op:
        batch_op.drop_column('late_submission')

    # ### end Alembic commands ###
