"""Add EmploymentTerminationHistory table

Revision ID: ca044348b742
Revises: 0021065a1e01
Create Date: 2025-09-20 08:28:29.066865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca044348b742'
down_revision = '0021065a1e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_termination_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('terminated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['terminated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employment_termination_history')
    # ### end Alembic commands ###
