"""Split credits into vacation and sick leave

Revision ID: cac75cb0bfb5
Revises: ca044348b742
Create Date: 2025-09-22 12:41:42.001989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cac75cb0bfb5'
down_revision = 'ca044348b742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type', sa.String(length=20), nullable=False))

    with op.batch_alter_table('employee_credits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacation_earned', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vacation_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vacation_remaining', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sick_earned', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sick_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sick_remaining', sa.Float(), nullable=True))
        batch_op.drop_column('total_credits')
        batch_op.drop_column('remaining_credits')
        batch_op.drop_column('used_credits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_credits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_credits', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('remaining_credits', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_credits', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('sick_remaining')
        batch_op.drop_column('sick_used')
        batch_op.drop_column('sick_earned')
        batch_op.drop_column('vacation_remaining')
        batch_op.drop_column('vacation_used')
        batch_op.drop_column('vacation_earned')

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_column('leave_type')

    # ### end Alembic commands ###
