"""Add permit modules: Leave, Travel Order, Clearance Form, COE

Revision ID: cae2f57b2c9b
Revises: 0bdaf396cab0
Create Date: 2025-05-20 21:24:19.884044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae2f57b2c9b'
down_revision = '0bdaf396cab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('permit_type', sa.Enum('Leave', 'Travel Order', 'Clearance Form', 'Certification of Employment', name='permit_type_enum'), nullable=False),
    sa.Column('date_requested', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('hr_remarks', sa.Text(), nullable=True),
    sa.Column('date_released', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clearance_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=True),
    sa.Column('clearance_purpose', sa.String(length=255), nullable=True),
    sa.Column('other_purpose', sa.String(length=255), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['permit_id'], ['permit_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_id')
    )
    op.create_table('coe_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permit_id'], ['permit_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_id')
    )
    op.create_table('leave_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=True),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('working_days', sa.String(length=50), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permit_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_id')
    )
    op.create_table('travel_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('date_departure', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['permit_id'], ['permit_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_orders')
    op.drop_table('leave_applications')
    op.drop_table('coe_requests')
    op.drop_table('clearance_forms')
    op.drop_table('permit_requests')
    # ### end Alembic commands ###
