"""Add final ratings to IPCR and OPCR

Revision ID: daab3ebbac15
Revises: 2d45cd372e29
Create Date: 2025-05-19 16:53:56.254334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daab3ebbac15'
down_revision = '2d45cd372e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcrs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_overall_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_average_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('adjective_rating', sa.String(length=50), nullable=True))

    with op.batch_alter_table('opcrs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_overall_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_average_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('adjective_rating', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcrs', schema=None) as batch_op:
        batch_op.drop_column('adjective_rating')
        batch_op.drop_column('final_average_rating')
        batch_op.drop_column('final_overall_rating')

    with op.batch_alter_table('ipcrs', schema=None) as batch_op:
        batch_op.drop_column('adjective_rating')
        batch_op.drop_column('final_average_rating')
        batch_op.drop_column('final_overall_rating')

    # ### end Alembic commands ###
