"""Add attachment to travel_orders and reason to coe_requests

Revision ID: dbcac858f462
Revises: 6a397237ba96
Create Date: 2025-09-25 22:32:04.192400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcac858f462'
down_revision = '6a397237ba96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coe_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    with op.batch_alter_table('coe_requests', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
