"""Added login_id to Users

Revision ID: e8c24aa7c941
Revises: 54a77192b2a5
Create Date: 2025-04-28 11:36:12.591555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c24aa7c941'
down_revision = '54a77192b2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_id', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['login_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('login_id')

    # ### end Alembic commands ###
