"""Add nullable tracking_id to TravelOrder

Revision ID: e94107c74974
Revises: 06b2944ba830
Create Date: 2025-05-22 22:36:32.501799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e94107c74974'
down_revision = '06b2944ba830'
branch_labels = None
depends_on = None


def upgrade():
    # First, add the column as nullable (no constraints yet)
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_id', sa.String(length=50), nullable=True))

    # Set all existing tracking_id values to NULL (in case any are empty strings)
    op.execute("UPDATE travel_orders SET tracking_id = NULL")

    # Now safely add the unique constraint
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tracking_id', ['tracking_id'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('tracking_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
