"""Removed description and salary_grade from positions, added type

Revision ID: edebab0bc9a5
Revises: 61f57844276f
Create Date: 2025-04-29 21:11:31.578879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edebab0bc9a5'
down_revision = '61f57844276f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.drop_column('salary_grade')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('salary_grade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
