"""update travel_logs table

Revision ID: ef69ccd01e67
Revises: 0061934e3b7f
Create Date: 2025-05-23 00:05:37.130956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef69ccd01e67'
down_revision = '0061934e3b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_logs', schema=None) as batch_op:
        batch_op.alter_column('log_date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_logs', schema=None) as batch_op:
        batch_op.alter_column('log_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
