"""Add CasualEmployeeHistory table

Revision ID: f2bafa37cad9
Revises: 73a0822e7ae3
Create Date: 2025-09-01 21:28:02.599198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bafa37cad9'
down_revision = '73a0822e7ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casual_employee_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('equivalent_salary', sa.String(length=100), nullable=True),
    sa.Column('daily_wage', sa.Float(), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casual_employee_history')
    # ### end Alembic commands ###
